package jaiz.jaizmod.item;

import jaiz.jaizmod.JaizMod;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.block.Blocks;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ModItemGroups {
    public static final ItemGroup JAIZMOD_GROUP = Registry.register(Registries.ITEM_GROUP, Identifier.of(JaizMod.MOD_ID, "_jaizmod"),
            FabricItemGroup.builder().displayName(Text.translatable("itemgroup._jaizmod"))
                    .icon(() -> new ItemStack(ModItems.CHISELED_PLATED_CALCITE.asItem())).entries((displayContext, entries) -> {
                        // things go here

                        entries.add(ModItems.CHISELED_PLATED_CALCITE);
                        entries.add(ModItems.PLATED_CALCITE);
                        entries.add(ModItems.SILK);
                        entries.add(ModItems.RARE_SPICES);
                        entries.add(ModItems.GOURMET_MEAL);
                        entries.add(ModItems.ORIGAMI_HAIRBALL_MUSIC_DISC);
                        entries.add(ModItems.BATTERED_AXE_REMNANT);
                        entries.add(ModItems.BATTERED_AXE);
                        entries.add(ModItems.OBSIDIAN_SHARD);
                        entries.add(ModItems.WEDGE_OBSIDIAN_SHARD);
                        entries.add(ModItems.SHARP_OBSIDIAN_SHARD);
                        entries.add(ModItems.OBSIDIAN_DAGGER);
                        entries.add(ModItems.WEDGE_OBSIDIAN_DAGGER);
                        entries.add(ModItems.SHARP_OBSIDIAN_DAGGER);
                        entries.add(ModItems.OBSIDIAN_SWORD);
                        entries.add(ModItems.WEDGE_OBSIDIAN_SWORD);
                        entries.add(ModItems.SHARP_OBSIDIAN_SWORD);
                        entries.add(ModItems.WEDGE_REGULAR_OBSIDIAN_SWORD);
                        entries.add(ModItems.SHARP_WEDGE_OBSIDIAN_SWORD);
                        entries.add(ModItems.SHARP_REGULAR_OBSIDIAN_SWORD);
                        entries.add(ModItems.MACUAHUITL);
                        entries.add(ModItems.PETRIFIED_ARMOR_TRIM_SMITHING_TEMPLATE);
                        entries.add(ModItems.MIMIC_POT);
                        entries.add(ModItems.BANDIT_SPAWN_EGG);
                        entries.add(ModItems.FANCY_WHITE_WOOL);
                        entries.add(ModItems.FANCY_LIGHT_GRAY_WOOL);
                        entries.add(ModItems.FANCY_GRAY_WOOL);
                        entries.add(ModItems.FANCY_BLACK_WOOL);
                        entries.add(ModItems.FANCY_BROWN_WOOL);
                        entries.add(ModItems.FANCY_RED_WOOL);
                        entries.add(ModItems.FANCY_ORANGE_WOOL);
                        entries.add(ModItems.FANCY_YELLOW_WOOL);
                        entries.add(ModItems.FANCY_LIME_WOOL);
                        entries.add(ModItems.FANCY_GREEN_WOOL);
                        entries.add(ModItems.FANCY_CYAN_WOOL);
                        entries.add(ModItems.FANCY_LIGHT_BLUE_WOOL);
                        entries.add(ModItems.FANCY_BLUE_WOOL);
                        entries.add(ModItems.FANCY_PURPLE_WOOL);
                        entries.add(ModItems.FANCY_MAGENTA_WOOL);
                        entries.add(ModItems.FANCY_PINK_WOOL);
                        entries.add(ModItems.FANCY_WHITE_CARPET);
                        entries.add(ModItems.FANCY_LIGHT_GRAY_CARPET);
                        entries.add(ModItems.FANCY_GRAY_CARPET);
                        entries.add(ModItems.FANCY_BLACK_CARPET);
                        entries.add(ModItems.FANCY_BROWN_CARPET);
                        entries.add(ModItems.FANCY_RED_CARPET);
                        entries.add(ModItems.FANCY_ORANGE_CARPET);
                        entries.add(ModItems.FANCY_YELLOW_CARPET);
                        entries.add(ModItems.FANCY_LIME_CARPET);
                        entries.add(ModItems.FANCY_GREEN_CARPET);
                        entries.add(ModItems.FANCY_CYAN_CARPET);
                        entries.add(ModItems.FANCY_LIGHT_BLUE_CARPET);
                        entries.add(ModItems.FANCY_BLUE_CARPET);
                        entries.add(ModItems.FANCY_PURPLE_CARPET);
                        entries.add(ModItems.FANCY_MAGENTA_CARPET);
                        entries.add(ModItems.FANCY_PINK_CARPET);
                        entries.add(ModItems.GILDED_CHISELED_SANDSTONE);
                        entries.add(ModItems.GILDED_CUT_SANDSTONE);
                        entries.add(ModItems.GILDED_SANDSTONE);
                        entries.add(ModItems.TERRACOTTA_BRICKS);
                        entries.add(ModItems.TERRACOTTA_BRICK_STAIRS);
                        entries.add(ModItems.TERRACOTTA_BRICK_WALL);
                        entries.add(ModItems.TERRACOTTA_BRICK_SLAB);
                        entries.add(ModItems.DESERT_OAK_PLANKS);
                        entries.add(ModItems.DESERT_OAK_DOOR);
                        entries.add(ModItems.DESERT_OAK_TRAPDOOR);
                        entries.add(ModItems.DESERT_OAK_FENCE);
                        entries.add(ModItems.DESERT_OAK_FENCE_GATE);
                        entries.add(ModItems.DESERT_OAK_SLAB);
                        entries.add(ModItems.DESERT_OAK_STAIRS);
                        entries.add(ModItems.DESERT_OAK_SIGN);
                        entries.add(ModItems.DESERT_OAK_HANGING_SIGN);
                        entries.add(ModItems.DESERT_OAK_BUTTON);
                        entries.add(ModItems.DESERT_OAK_PRESSURE_PLATE);
                        entries.add(ModItems.DESERT_OAK_BOAT);
                        entries.add(ModItems.DESERT_OAK_CHEST_BOAT);
                        entries.add(ModItems.SPICE_BARREL);
                        entries.add(ModItems.DESERT_OAK_SAPLING);
                        entries.add(ModItems.DESERT_OAK_LEAVES);
                        entries.add(ModItems.DESERT_OAK_LOG);
                        entries.add(ModItems.DESERT_OAK_WOOD);
                        entries.add(ModItems.STRIPPED_DESERT_OAK_LOG);
                        entries.add(ModItems.STRIPPED_DESERT_OAK_WOOD);
                        entries.add(ModItems.FOSSIL_SOIL);
                        entries.add(ModItems.PETRIFIED_DIRT);
                        entries.add(ModItems.AMETHYST_HORN);
                        entries.add(ModItems.AIR_HORN);
                        entries.add(ModItems.ANCIENT_HORN);
                        entries.add(ModItems.CATERPILLAR_SPAWN_EGG);
                        entries.add(ModItems.BUTTERFLY_SPAWN_EGG);
                        entries.add(ModItems.DRAGONFLY_SPAWN_EGG);
                        entries.add(ModItems.FIREFLY_SWARM_SPAWN_EGG);
                        entries.add(ModItems.SNAIL_SPAWN_EGG);
                        entries.add(ModItems.FIREFLY_BOTTLE);
                        entries.add(ModItems.BUTTERFLY_BOTTLE);
                        entries.add(ModItems.DRAGONFLY_BOTTLE);
                        entries.add(ModItems.CATERPILLAR_BOTTLE);
                        entries.add(ModItems.SNAIL_BOTTLE);
                        entries.add(ModItems.ROTTEN_LOG);
                        entries.add(ModItems.ROTTEN_WOOD);
                        entries.add(ModItems.STRIPPED_ROTTEN_LOG);
                        entries.add(ModItems.STRIPPED_ROTTEN_WOOD);
                        entries.add(ModItems.ROTTEN_PLANKS);
                        entries.add(ModItems.ROTTEN_DOOR);
                        entries.add(ModItems.ROTTEN_TRAPDOOR);
                        entries.add(ModItems.ROTTEN_FENCE);
                        entries.add(ModItems.ROTTEN_FENCE_GATE);
                        entries.add(ModItems.ROTTEN_SLAB);
                        entries.add(ModItems.ROTTEN_STAIRS);
                        entries.add(ModItems.ROTTEN_SIGN);
                        entries.add(ModItems.ROTTEN_HANGING_SIGN);
                        entries.add(ModItems.ROTTEN_BUTTON);
                        entries.add(ModItems.ROTTEN_PRESSURE_PLATE);
                        entries.add(ModItems.ROT_BLOCK);
                        entries.add(ModItems.ROT_ROOTS);
                        entries.add(ModItems.ROTTEN_BOAT);
                        entries.add(ModItems.ROTTEN_CHEST_BOAT);
                        entries.add(ModItems.DRIED_LEAVES);
                        entries.add(ModItems.DEAD_LEAVES);
                        entries.add(ModItems.SHELF_MUSHROOM_BLOCK);
                        entries.add(ModItems.COCOON_BLOCK);
                        entries.add(ModItems.COLUMBINE);
                        entries.add(ModItems.CALLALILY_WHITE);
                        entries.add(ModItems.CALLALILY_LILAC);
                        entries.add(ModItems.CALLALILY_PINK);
                        entries.add(ModItems.CALLALILY_PURPLE);
                        entries.add(ModItems.CALLALILY_YELLOW);
                        entries.add(ModItems.WHITE_FLORAL_VEIL);
                        entries.add(ModItems.PINK_FLORAL_VEIL);
                        entries.add(ModItems.YELLOW_FLORAL_VEIL);
                        entries.add(ModItems.IVY);
                        entries.add(ModItems.UNDERGROWTH);
                        entries.add(ModItems.MAHOGANY_PLANKS);
                        entries.add(ModItems.MAHOGANY_STAIRS);
                        entries.add(ModItems.MAHOGANY_SLAB);
                        entries.add(ModItems.MAHOGANY_LOG);
                        entries.add(ModItems.MAHOGANY_LEAVES);
                        entries.add(ModItems.MAHOGANY_SAPLING);
                        entries.add(ModItems.MAHOGANY_WOOD);
                        entries.add(ModItems.STRIPPED_MAHOGANY_LOG);
                        entries.add(ModItems.STRIPPED_MAHOGANY_WOOD);
                        entries.add(ModItems.MAHOGANY_DOOR);
                        entries.add(ModItems.MAHOGANY_TRAPDOOR);
                        entries.add(ModItems.MAHOGANY_BUTTON);
                        entries.add(ModItems.MAHOGANY_PRESSURE_PLATE);
                        entries.add(ModItems.MAHOGANY_FENCE);
                        entries.add(ModItems.MAHOGANY_FENCE_GATE);
                        entries.add(ModItems.MAHOGANY_HANGING_SIGN);
                        entries.add(ModItems.MAHOGANY_SIGN);
                        entries.add(ModItems.MAHOGANY_BOAT);
                        entries.add(ModItems.MAHOGANY_CHEST_BOAT);
                        entries.add(ModItems.SLIMEY_STONE);
                        entries.add(ModItems.SLIME_DRIP);
                        entries.add(ModItems.GUANO);
                        entries.add(ModItems.GUANO_PILE);
                        entries.add(ModItems.FRUIT_BAT_SPAWN_EGG);
                        entries.add(ModItems.TEAPOTBLOCK);
                        entries.add(ModItems.UNFIRED_TEA_CUP);
                        entries.add(ModItems.TEA_CUP);
                        entries.add(ModItems.CHORUS_FRUIT_TEA);
                        entries.add(ModItems.FLOWER_TEA);
                        entries.add(ModItems.GLOW_BERRY_TEA);
                        entries.add(ModItems.GUNPOWDER_GREEN_TEA);
                        entries.add(ModItems.HERBAL_TEA);
                        entries.add(ModItems.KOMBUCHA_TEA);
                        entries.add(ModItems.NETHER_FUNGUS_TEA);
                        entries.add(ModItems.WARPED_NETHER_FUNGUS_TEA);
                        entries.add(ModItems.PITCHER_PLANT_TEA);
                        entries.add(ModItems.PUMPKIN_SPICE_TEA);
                        entries.add(ModItems.SPORE_BLOSSOM_TEA);
                        entries.add(ModItems.TORCH_FLOWER_TEA);
                        entries.add(ModItems.WITHER_ROSE_TEA);
                        entries.add(ModItems.NOVEL_TEA);
                        entries.add(ModItems.DYNAMITE);
                        entries.add(ModItems.GLOWING_SPYGLASS);
                        entries.add(ModItems.WATER_TORCH);
                        entries.add(ModItems.GLOW_BALL);
                        entries.add(ModItems.BIOLUMINESCENT_BOTTLE);
                        entries.add(ModItems.SNIFFER_WOOL);
                        entries.add(ModItems.SNIFFER_CARPET);
                        entries.add(ModItems.SNIFFER_TUFT);
                        entries.add(ModItems.SNIFFER_MEAT);
                        entries.add(ModItems.COOKED_SNIFFER_MEAT);
                        entries.add(ModItems.ANCIENT_SPROUT);
                        entries.add(ModItems.BLOOMING_IVY_BLOCK);
                        entries.add(ModItems.BLOOMING_IVY);
                    }).build());

    public static void registerItemGroups() {
        JaizMod.LOGGER.info("Registering Item Groups");
    }
}
